export interface BriefingEmailInput {
  to: string;
  name: string;
  briefingDate: string;
  aiSummary: string;
  recommendations: string[];
}

export function isEmailDeliveryConfigured(): boolean {
  return Boolean(
    process.env.POSTMARK_SERVER_TOKEN?.trim() &&
      process.env.POSTMARK_FROM_EMAIL?.trim(),
  );
}

export async function sendBriefingEmail(input: BriefingEmailInput): Promise<void> {
  const token = process.env.POSTMARK_SERVER_TOKEN?.trim();
  const from = process.env.POSTMARK_FROM_EMAIL?.trim();

  if (!token || !from) {
    throw new Error(
      'POSTMARK_SERVER_TOKEN and POSTMARK_FROM_EMAIL are required for email delivery',
    );
  }

  const recList =
    input.recommendations.length > 0
      ? `<ul>${input.recommendations.map((r) => `<li>${escapeHtml(r)}</li>`).join('')}</ul>`
      : '';

  const htmlBody = `
    <h2>Daily Executive Brief — ${escapeHtml(input.briefingDate)}</h2>
    <p>Hi ${escapeHtml(input.name)},</p>
    <div>${escapeHtml(input.aiSummary).replace(/\n/g, '<br/>')}</div>
    <h3>Recommended actions</h3>
    ${recList}
    <p><small>Generated by Job Search Command Center</small></p>
  `.trim();

  const res = await fetch('https://api.postmarkapp.com/email', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'X-Postmark-Server-Token': token,
    },
    body: JSON.stringify({
      From: from,
      To: input.to,
      Subject: `Your job search daily brief — ${input.briefingDate}`,
      HtmlBody: htmlBody,
      MessageStream: 'outbound',
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Postmark send failed (${res.status}): ${body.slice(0, 200)}`);
  }
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
